<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>_1109</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="C:\Users\User\source\repos\1109\1109\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <None Include="C:\Users\User\source\repos\1109\1109\.editorconfig" />
  </ItemGroup>

</Project>
